export const controlContextMenu = [
    {
        icon:"cut.svg",
        text:"Cut",
        values:[],
        disabled:false
    },
    {
        icon:"copy.svg",
        text:"Copy",
        values:[],
        disabled:false
    },
    {
        icon:"paste.svg",
        text:"Paste",
        values:[],
        disabled:false
    },
    {
        icon:"",
        text:"Delete",
        values:[],
        disabled:false
    },
    {
        icon:"object-property.svg",
        text:"Properties",
        values:[],
        disabled:false
    },
    {
        icon:"view-code.svg",
        text:"View Code",
        values:[],
        disabled:false
    },
    {
        icon:"",
        text:"Align",
        values:[{icon:"",
        text:"Align",
        values:[],
        disabled:false},
        {icon:"",
        text:"Lefts",
        values:[],
        disabled:false},
        {icon:"",
        text:"Centers",
        values:[],
        disabled:false},
        {icon:"",
        text:"Rights",
        values:[],
        disabled:false},
        {icon:"",
        text:"Tops",
        values:[],
        disabled:false},
        {icon:"",
        text:"Middles",
        values:[],
        disabled:false},
        {icon:"",
        text:"Bottoms",
        values:[],
        disabled:false},
        {icon:"",
        text:"To Grids",
        values:[],
        disabled:false}
    ],
        disabled:false
    },
    {
        icon:"",
        text:"Make Same Size",
        values:[{icon:"",
        text:"Width",
        values:[],
        disabled:false},
        {icon:"",
        text:"Height",
        values:[],
        disabled:false},
        {icon:"",
        text:"Both",
        values:[],
        disabled:false}],
        disabled:false
    },
    {
        icon:"group.svg",
        text:"Group",
        values:[],
        disabled:false
    },
    {
        icon:"control-forward.svg",
        text:"Bring Forward",
        values:[],
        disabled:false
    },
    {
        icon:"control-backward.svg",
        text:"Send Backward",
        values:[],
        disabled:false
    }
]